<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSQrkZTI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSQrkZTI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSQrkZTI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSQrkZTI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSQrkZTI\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'SQrkZTI',
    'container.build_id' => 'ad27759e',
    'container.build_time' => 1548681223,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSQrkZTI');
