<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXye2nOW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXye2nOW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXye2nOW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXye2nOW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXye2nOW\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Xye2nOW',
    'container.build_id' => '2383ffab',
    'container.build_time' => 1547817438,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXye2nOW');
